name       : zimg
version    : 2.7.1
release    : 5
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.7.1.tar.gz : fa1d59a2a1ba330e4f3e0460e913fe41dfdf9c6ae950ffb7b73b531fe18ead8f
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
