name       : zimg
version    : 3.0.2
release    : 12
source     :
    - https://github.com/sekrit-twc/zimg/archive/refs/tags/release-3.0.2.tar.gz : b9eadf1df12ae8395ba781f2468965d411b21abbebbebeae3651d492227d4633
license    : WTFPL
component  : multimedia.library
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
