name       : zimg
version    : 2.3
release    : 1
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.3.tar.gz : 09962385f986dbcfd8ed6160cdafc2bc57bef8c6bfb3ca3a4bcaa482f09c06fa
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
