name       : zimg
version    : 3.0.3
release    : 13
source     :
    - https://github.com/sekrit-twc/zimg/archive/refs/tags/release-3.0.3.tar.gz : 5e002992bfe8b9d2867fdc9266dc84faca46f0bfd931acc2ae0124972b6170a7
license    : WTFPL
component  : multimedia.library
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
