name       : zimg
version    : 2.6.3
release    : 4
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.6.3.tar.gz : a701e9ffbe3ad379e84d8720cf6220afb9c6946d761048fb77544325870cc2cb
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
