name       : zimg
version    : 3.0.1
release    : 11
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-3.0.1.tar.gz : c50a0922f4adac4efad77427d13520ed89b8366eef0ef2fa379572951afcc73f
license    : WTFPL
component  : multimedia.library
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
