name       : zimg
version    : 3.0.5
release    : 15
source     :
    - https://github.com/sekrit-twc/zimg/archive/refs/tags/release-3.0.5.tar.gz : a9a0226bf85e0d83c41a8ebe4e3e690e1348682f6a2a7838f1b8cbff1b799bcf
license    : WTFPL
component  : multimedia.library
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
