name       : zimg
version    : 2.7.5
release    : 6
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.7.5.tar.gz : 0fbefe23cd677f4d902dcad40c4ef078a347454630168106e6eed4cf91a217ff
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
