name       : zimg
version    : 2.9.2
release    : 9
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.9.2.tar.gz : 10403c2964fe11b559a7ec5e081c358348fb787e26b91ec0d1f9dd7c01d1cd7b
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
