name       : zimg
version    : 2.9.3
release    : 10
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.9.3.tar.gz : a15c0483fbe945ffe695a1a989bc43b3381c8bf33e2d1760464ec21d32cdf30b
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
