name       : zimg
version    : 2.5.1
release    : 3
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.5.1.tar.gz : deb85887081cab7fa9c492b588900d60d6466e61ee8ea51a84ca280688d93de9
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
