name       : zimg
version    : '2.5'
release    : 2
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.5.tar.gz : 50b2bcc49e51cd36011a0c363ff914a81b6f161aefdffeaa2bc4a4627c13784d
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
