name       : zimg
version    : '2.8'
release    : 7
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.8.tar.gz : a8f9d65c95ce6e8050d83d0417b109aabc94d2c7ba65cf2d8039840d162ad876
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
