name       : zimg
version    : 2.9.1
release    : 8
source     :
    - https://github.com/sekrit-twc/zimg/archive/release-2.9.1.tar.gz : 8efa0c381aa6a9bcd5ea4ae22ad06dccf6c1dc705c394547de016951d1946154
license    : BSD-3-Clause
component  : programming
summary    : Project zimg is a light image storage and processing system.
description: |
    Project zimg is a light image storage and processing system.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
